version: "3"
services:
  backend:
    image: mingfaicheung/spring-boot-react-fullstack:11.3.2023.12.22.10
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
