version: "3"
services:
  backend:
    image: mingfaicheung/spring-boot-react-fullstack:6.3.2023.4.53.35
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
